### ISSUE TITLE
Working examples

### ISSUE THREAD

**Issue by mindplay-dk** [kyegomez/LM-Infinite#4]
Has this library been integrated anywhere? I looked for package dependents, and there aren't any.

As I [asked here](https://twitter.com/mindplaydk/status/1698689931206345002):

> wait, so do I understand correctly, this not only generalizes to different models - it also speeds them up by almost 3 times??

You replied with "affirmative", so I suppose you must have actually tested it?

I'm really eager to see this in action. 😊

(FYI, I'm just a developer, not an ML expert - so in this context, I'm just and end user hoping for a truly useful LLM to help me organize and research details for a project I'm working on.)

Has this technique been implemented anywhere else?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/LM-Infinite/issues/4">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/LM-Infinite/issues/4/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/LM-Infinite/issues/4/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@mindplay-dk Hey perhaps my implementation has not leveraged a 3x speedup but the paper reports a 3x speedup!
I have implemented the speculative decoding 

https://github.com/kyegomez/zeta/blob/main/zeta/nn/architecture/auto_regressive_wrapper.py

**Comment by mindplay-dk** [comment]
for `zetascale`, I see two dependents on libraries.io but apparently they don't list python dependents. do you know that they are?

(btw the zeta website is down.)

**Comment by mindplay-dk** [comment]
are there any projects implementing this yet? (why not?)

**Comment by mindplay-dk** [comment]
@kyegomez any news?

for all the hype this paper received, how come no one is implementing this?

I figured we'd have unbounded context everywhere by now. 😌
