### ISSUE TITLE
Is the implementation the same as in the paper

### ISSUE THREAD

**Issue by jiezhangGt** [kyegomez/LM-Infinite#6]
I ported this code to gpt_nexo model's decoding,  and the effect was severely degraded。

seq_len = 8192
l_pretrain = 4096
n_global = 2048

**Comment by kyegomez** [comment]
@jiezhangGt Hey this is a rough implementation that I'm working on everyday, how was the effect severely degraded? Can you provide more insight? What is your baseline vs LM Infinite?
